#!/usr/bin/env ansible-playbook
---
- name: create a new docker container
  hosts: localhost
  vars:
    container: webcontainer
  tasks:
    - name: start a docker container with bash
      docker: image=ubuntu name={{ container }} detach=yes tty=yes command=bash
    - name: add it to the inventory
      add_host: name={{ container }} ansible_python_interpreter=/usr/bin/python2.7

- name: test the docker connection
  connection: dockerlocal
  hosts: webcontainer

  tasks:
    - name: update apt repo (raw)
      raw: apt-get update
    - name: install python 2.7 (raw)
      raw: apt-get install -y python2.7
    - name: install nginx
      apt: name=nginx
    - name: fetch the timezone file
      fetch: src=/etc/timezone dest=.

- hosts: localhost
  vars:
    container: webcontainer
  tasks:
    - name: stop the container
      command: docker kill {{ container }}
