#!/usr/bin/env ansible-playbook
---
- name: test the docker connection
  connection: docker
  hosts: mytest
  gather_facts: False

  tasks:
    - name: install nginx
      apt: name=nginx
    - name: fetch the timezone file
      fetch: src=/etc/timezone dest=.
