#!/usr/bin/env ansible-playbook
---
- name: create an ipython container
  hosts: ipython
  connection: docker
  vars:
    image: lorin/ipython:v1

  pre_tasks:
    - name: start up a docker container by running bash
      local_action: docker image=ubuntu name={{ inventory_hostname }} detach=yes tty=yes command=bash

    - name: update apt repo (raw)
      raw: apt-get update

    - name: install python 2.7 (raw)
      raw: apt-get install -y python2.7

  roles:
    - ipython

  post_tasks:
    - name: capture the container to an image
      local_action: command docker commit {{ inventory_hostname }} {{ image }}
    - name: stop the current running container
      local_action: command docker kill {{ inventory_hostname }}
