---
- name: install packages
  apt: name={{ item }}
  with_items:
    - build-essential
    - gfortran
    - libfreetype6-dev
    - liblapack-dev
    - libopenblas-dev
    - libpng12-dev
    - libpq-dev
    - libzmq3-dev
    - pandoc
    - pkg-config
    - python-pip
    - python2.7-dev

- name: install packages with pip
  pip: name={{ item }}
  with_items:
    - numpy
    - scipy
    - cython
    - pandas
    - matplotlib
    - seaborn
    - patsy
    - statsmodels
    - ggplot
    - ipython[all]
    - psycopg2
